services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    volumes:
      - ./:/var/www/html:delegated
      - ./var/log:/var/www/html/var/log
    environment:
      APP_ENV: dev
      APP_SECRET: "${APP_SECRET:-your_secure_symfony_secret}" # Replace with a strong secret
      DATABASE_URL: "mysql://user:password@symfony_db:3306/dbname"
      REDIS_HOST: symfony_redis
      REDIS_PORT: 6379
    depends_on:
      symfony_db:
        condition: service_healthy
      symfony_redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "-r", "exit(file_exists('/var/www/html/var/cache/dev') ? 0 : 1);"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:1.21-alpine
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  symfony_db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  symfony_redis:
    image: redis:7-alpine
    container_name: symfony_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: symfony_db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      symfony_db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network

volumes:
  db_data:
  redis_data:

networks:
  app_network:
    driver: bridge
